version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_Strong_Password_123!"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/OpenBudget.Bot/Dockerfile
    ports:
      - "4041:4041"
    environment:
      - ASPNETCORE_HTTP_PORTS=4041
      - ConnectionStrings__DefaultConnection=Server=db;Database=OpenBudgetDb;User Id=sa;Password=Your_Strong_Password_123!;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  ui:
    build:
      context: ./src/mini-app
      dockerfile: Dockerfile
    ports:
      - "4040:80"
    depends_on:
      - api

volumes:
  sql_data:
