// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenBudget.Infrastructure.Data;

#nullable disable

namespace OpenBudget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821132442_AddBotCommandEntity")]
    partial class AddBotCommandEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenBudget.Domain.Entities.BotCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BotCommands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedRoles = "All",
                            CommandText = "/start",
                            Description = "Botni ishga tushirish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            AllowedRoles = "All",
                            CommandText = "/cancel",
                            Description = "Jarayonni bekor qilish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            AllowedRoles = "All",
                            CommandText = "🔙 Bekor qilish",
                            Description = "Jarayonni bekor qilish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            AllowedRoles = "All",
                            CommandText = "/info",
                            Description = "Loyiha ma'lumotlari",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            AllowedRoles = "All",
                            CommandText = "ℹ️ Loyiha ma'lumotlari",
                            Description = "Loyiha ma'lumotlari",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            AllowedRoles = "Guest",
                            CommandText = "/request",
                            Description = "Brokerlik so'rovi yuborish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            AllowedRoles = "Guest",
                            CommandText = "📩 Brokerlik so'rovi yuborish",
                            Description = "Brokerlik so'rovi yuborish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/vote",
                            Description = "Yangi ovoz qo'shish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "📝 Ovoz qo'shish",
                            Description = "Yangi ovoz qo'shish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/myvotes",
                            Description = "Mening ovozlarim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "📋 Mening ovozlarim",
                            Description = "Mening ovozlarim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/mystats",
                            Description = "Shaxsiy statistika",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "📊 Statistikam",
                            Description = "Shaxsiy statistika",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "📊 Mening statistikam",
                            Description = "Shaxsiy statistika",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/myconfirmations",
                            Description = "Mening tasdiqlanganlarim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "✅ Mening tasdiqlanganlarim",
                            Description = "Mening tasdiqlanganlarim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/guests",
                            Description = "Mehmonlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "🚶‍♂️ Mehmonlar ro'yxati",
                            Description = "Mehmonlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/brokers",
                            Description = "Brokerlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "👥 Brokerlar ro'yxati",
                            Description = "Brokerlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "➕ Broker qo'shish",
                            Description = "Yangi broker qo'shish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/confirm",
                            Description = "Ovoz tasdiqlash",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "✅ Ovoz tasdiqlash",
                            Description = "Ovoz tasdiqlash",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/pendingconfirmations",
                            Description = "Kutishdagi tasdiqlar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "✅ OB da tasdiqlanganlar",
                            Description = "Kutishdagi tasdiqlar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/smshistory",
                            Description = "SMS lar tarixi",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "📜 SMS lar tarixi",
                            Description = "SMS lar tarixi",
                            IsActive = true
                        },
                        new
                        {
                            Id = 28,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/adminstats",
                            Description = "Brokerlar statistikasi",
                            IsActive = true
                        },
                        new
                        {
                            Id = 29,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "📊 Brokerlar statistikasi",
                            Description = "Brokerlar statistikasi",
                            IsActive = true
                        },
                        new
                        {
                            Id = 30,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/broadcast",
                            Description = "Ommaviy xabar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 31,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "📨 Ommaviy xabar",
                            Description = "Ommaviy xabar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 32,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "🔲 QR Kod yuborish",
                            Description = "QR Kod yuborish",
                            IsActive = true
                        },
                        new
                        {
                            Id = 33,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/globalstats",
                            Description = "Global Statistika",
                            IsActive = true
                        },
                        new
                        {
                            Id = 34,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "🌍 Global Statistika",
                            Description = "Global Statistika",
                            IsActive = true
                        },
                        new
                        {
                            Id = 35,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/admins",
                            Description = "Adminlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 36,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "🛡 Adminlar ro'yxati",
                            Description = "Adminlar ro'yxati",
                            IsActive = true
                        },
                        new
                        {
                            Id = 37,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/assignadmin",
                            Description = "Admin tayinlash",
                            IsActive = true
                        },
                        new
                        {
                            Id = 38,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "🛡 Admin tayinlash",
                            Description = "Admin tayinlash",
                            IsActive = true
                        },
                        new
                        {
                            Id = 39,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/groups",
                            Description = "Ulangan guruhlar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 40,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "📢 Ulangan guruhlar",
                            Description = "Ulangan guruhlar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 41,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/settings",
                            Description = "Sozlamalar",
                            IsActive = true
                        },
                        new
                        {
                            Id = 42,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "⚙️ Sozlamalar",
                            Description = "Sozlamalar",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.BotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("BotSettings", (string)null);
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.TelegramGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("InitiativeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("TelegramGroups");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BotState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ConfirmedByAdminId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.VoteConfirmation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastNDigits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MatchedVoteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("MatchedVoteId");

                    b.ToTable("VoteConfirmations");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.Vote", b =>
                {
                    b.HasOne("OpenBudget.Domain.Entities.User", "Broker")
                        .WithMany("CollectedVotes")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenBudget.Domain.Entities.User", "ConfirmedByAdmin")
                        .WithMany("ConfirmedVotes")
                        .HasForeignKey("ConfirmedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broker");

                    b.Navigation("ConfirmedByAdmin");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.VoteConfirmation", b =>
                {
                    b.HasOne("OpenBudget.Domain.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBudget.Domain.Entities.Vote", "MatchedVote")
                        .WithMany()
                        .HasForeignKey("MatchedVoteId");

                    b.Navigation("Admin");

                    b.Navigation("MatchedVote");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.User", b =>
                {
                    b.Navigation("CollectedVotes");

                    b.Navigation("ConfirmedVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
