// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenBudget.Infrastructure.Data;

#nullable disable

namespace OpenBudget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821134800_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenBudget.Domain.Entities.BotCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BotCommands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedRoles = "All",
                            CommandText = "/start",
                            Description = "Botni ishga tushirish va foydalanuvchi roliga (Guest/Broker/Admin) mos bosh menyuni ko'rsatish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            AllowedRoles = "All",
                            CommandText = "/cancel",
                            Description = "Joriy boshlangan har qanday jarayonni bekor qilish va boshlang'ich holatga qaytish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            AllowedRoles = "All",
                            CommandText = "/info",
                            Description = "Loyiha, OpenBudget haqida va botdan qanday foydalanish to'g'risida asosiy ma'lumotlar.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            AllowedRoles = "Guest",
                            CommandText = "/request",
                            Description = "Yangi foydalanuvchilar (Guest) tomonidan Adminlarga Broker sifatida ro'yxatdan o'tish so'rovini yuborish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/vote",
                            Description = "Yangi ovoz qo'shish. Kiritish kerak: [TelefonNomer] [Soat:Minut] [Kun(ixtiyoriy)].",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/myvotes",
                            Description = "Broker o'zi kiritgan barcha (Pending/Confirmed) ovozlarning umumiy ro'yxati va holati.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/mystats",
                            Description = "Brokerning shaxsiy statistikasi: to'plagan tasdiqlangan ovozlar soni va umumiy ishlangan pullari.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            AllowedRoles = "Broker,Admin,SuperAdmin",
                            CommandText = "/myconfirmations",
                            Description = "Brokerning vaqt bo'yicha muvaffaqiyatli tasdiqlangan (Confirmed) ovozlari tarixi.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/guests",
                            Description = "Tizimga kirgan va so'rov yuborgan (hali tasdiqlanmagan) mehmonlar ro'yxatini ko'rish va ularni tasdiqlash.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/brokers",
                            Description = "Tasdiqlangan barcha faol brokerlar ro'yxati, ularning ma'lumotlari va tizimdan o'chirish imkoniyati.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/confirm",
                            Description = "SMS larni bittalab tasdiqlash. Kiritish kerak: [Oxirgi4Raqam] [Soat:Minut] [Kun(ixtiyoriy)].",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/pendingconfirmations",
                            Description = "Admin kiritgan, lekin hali brokerning ovozi bilan moslashmagan Kutishdagi (Pending) tasdiqlar ro'yxati.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/smshistory",
                            Description = "Admin tomonidan tizimga kiritilgan barcha muvaffaqiyatli, rad etilgan va kutilayotgan SMS lar tarixi.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/adminstats",
                            Description = "Barcha brokerlar orasida eng ko'p ovoz to'plaganlar reytingi va ularning umumlashgan faolligi.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            AllowedRoles = "Admin,SuperAdmin",
                            CommandText = "/broadcast",
                            Description = "Botdagi barcha brokerlar yoki foydalanuvchilarga bildirishnoma va e'lon yuborish (rasm, matn).",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/globalstats",
                            Description = "Butun tizimdagi umumiy yig'ilgan ovozlar soni, to'langan pullar va to'liq tizim holati.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/admins",
                            Description = "Tizimda boshqaruv huquqiga ega bo'lgan mavjud barcha Adminlar ro'yxatini ko'rish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/assignadmin",
                            Description = "Oddiy brokerlarni yoki foydalanuvchilarni Admin lavozimiga ko'tarish, yoki Adminlikdan olish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/groups",
                            Description = "Ovozlar haqida avtomatik hisobot yuborilishi uchun telegram guruhlarini botga ulash yoki o'chirish.",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            AllowedRoles = "SuperAdmin",
                            CommandText = "/settings",
                            Description = "Tizimning asosiy sozlamalari (ovoz narxi, avto-tasdiqlash vaqti chegarasi va boshqalar) ni o'zgartirish.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.BotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("BotSettings", (string)null);
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.TelegramGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("InitiativeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("TelegramGroups");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BotState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ConfirmedByAdminId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.VoteConfirmation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastNDigits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MatchedVoteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("MatchedVoteId");

                    b.ToTable("VoteConfirmations");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.Vote", b =>
                {
                    b.HasOne("OpenBudget.Domain.Entities.User", "Broker")
                        .WithMany("CollectedVotes")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenBudget.Domain.Entities.User", "ConfirmedByAdmin")
                        .WithMany("ConfirmedVotes")
                        .HasForeignKey("ConfirmedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Broker");

                    b.Navigation("ConfirmedByAdmin");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.VoteConfirmation", b =>
                {
                    b.HasOne("OpenBudget.Domain.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBudget.Domain.Entities.Vote", "MatchedVote")
                        .WithMany()
                        .HasForeignKey("MatchedVoteId");

                    b.Navigation("Admin");

                    b.Navigation("MatchedVote");
                });

            modelBuilder.Entity("OpenBudget.Domain.Entities.User", b =>
                {
                    b.Navigation("CollectedVotes");

                    b.Navigation("ConfirmedVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
